import os

SYSTEMS = [('Ag', 'Cu', 'O'),
    ('Ag', 'Mo', 'O'),
    ('Ag', 'O', 'P'),
    ('Ag', 'O', 'Sb'),
    ('Al', 'Ca', 'O', 'Si'),
    ('Al', 'Co', 'O'),
    ('Al', 'Cu', 'O'),
    ('Al', 'Er', 'O'),
    ('Al', 'Eu', 'O'),
    ('Al', 'Fe', 'O'),
    ('Al', 'Ga', 'O', 'P'),
    ('Al', 'Gd', 'O'),
    ('Al', 'K', 'O'),
    ('Al', 'La', 'O'),
    ('Al', 'Lu', 'O'),
    ('Al', 'Mg', 'O'),
    ('Al', 'Mn', 'O'),
    ('Al', 'Mo', 'O'),
    ('Al', 'N', 'Nd', 'O'),
    ('Al', 'Na', 'O', 'S'),
    ('Al', 'Nd', 'O'),
    ('Al', 'Ni', 'O'),
    ('Al', 'O', 'Pr'),
    ('Al', 'O', 'Si', 'Sr'),
    ('Al', 'O', 'Sr'),
    ('Al', 'O', 'Ta'),
    ('Al', 'O', 'Ti'),
    ('Al', 'O', 'W'),
    ('Al', 'O', 'Y'),
    ('Al', 'O', 'Zn'),
    ('As', 'Ba', 'O'),
    ('As', 'Co', 'La', 'O'),
    ('As', 'Co', 'Nd', 'O'),
    ('As', 'Cu', 'O'),
    ('As', 'Fe', 'La', 'O'),
    ('As', 'O', 'Y'),
    ('B', 'Ca', 'Na', 'O'),
    ('B', 'Co', 'Li', 'O'),
    ('Ba', 'Bi', 'O'),
    ('Ba', 'Ce', 'O'),
    ('Ba', 'Co', 'O'),
    ('Ba', 'Cr', 'O'),
    ('Ba', 'Cu', 'O'),
    ('Ba', 'Fe', 'O'),
    ('Ba', 'In', 'O'),
    ('Ba', 'Mn', 'O'),
    ('Ba', 'Mo', 'O'),
    ('Ba', 'Nb', 'O'),
    ('Ba', 'Nd', 'O'),
    ('Ba', 'O', 'P'),
    ('Ba', 'O', 'Pt'),
    ('Ba', 'O', 'Pu'),
    ('Ba', 'O', 'Ru'),
    ('Ba', 'O', 'Sb'),
    ('Ba', 'O', 'Sr', 'Ti'),
    ('Ba', 'O', 'Ta'),
    ('Ba', 'O', 'Te'),
    ('Ba', 'O', 'Th'),
    ('Ba', 'O', 'Ti'),
    ('Ba', 'O', 'U'),
    ('Ba', 'O', 'W'),
    ('Bi', 'Cr', 'O'),
    ('Bi', 'Dy', 'O'),
    ('Bi', 'Fe', 'O'),
    ('Bi', 'Ge', 'O'),
    ('Bi', 'In', 'O'),
    ('Bi', 'Ir', 'O'),
    ('Bi', 'K', 'O'),
    ('Bi', 'La', 'O'),
    ('Bi', 'Li', 'O'),
    ('Bi', 'Mn', 'O'),
    ('Bi', 'Mo', 'O'),
    ('Bi', 'Ni', 'O'),
    ('Bi', 'O', 'Ru'),
    ('Bi', 'O', 'Sc'),
    ('Bi', 'O', 'Sn'),
    ('Bi', 'O', 'Sr', 'Ta'),
    ('Bi', 'O', 'Te'),
    ('Bi', 'O', 'Ti'),
    ('Bi', 'O', 'V'),
    ('Bi', 'O', 'Zn'),
    ('C', 'Li', 'Na', 'O'),
    ('Ca', 'Cl', 'Cu', 'O'),
    ('Ca', 'Cl', 'O', 'Si'),
    ('Ca', 'Fe', 'O'),
    ('Ca', 'Ir', 'O'),
    ('Ca', 'Ni', 'O'),
    ('Ca', 'O', 'Pd'),
    ('Ca', 'O', 'Ru'),
    ('Ca', 'O', 'S'),
    ('Ca', 'O', 'Sb'),
    ('Ca', 'O', 'Sc'),
    ('Ca', 'O', 'Si'),
    ('Ca', 'O', 'Sn'),
    ('Ca', 'O', 'U'),
    ('Ca', 'O', 'W'),
    ('Ca', 'O', 'Zr'),
    ('Cd', 'Fe', 'O'),
    ('Cd', 'O', 'Si'),
    ('Cd', 'O', 'Ta'),
    ('Cd', 'O', 'Te'),
    ('Cd', 'O', 'Zn'),
    ('Ce', 'Dy', 'O'),
    ('Ce', 'Gd', 'O'),
    ('Ce', 'La', 'O'),
    ('Ce', 'Nd', 'O'),
    ('Ce', 'O', 'P'),
    ('Ce', 'O', 'Si'),
    ('Ce', 'O', 'Sm'),
    ('Ce', 'O', 'Ta'),
    ('Ce', 'O', 'Ti'),
    ('Ce', 'O', 'V'),
    ('Ce', 'O', 'Zr'),
    ('Co', 'Cu', 'O'),
    ('Co', 'Ge', 'O'),
    ('Co', 'Mg', 'O'),
    ('Co', 'Mn', 'O'),
    ('Co', 'Na', 'O'),
    ('Co', 'Nb', 'O'),
    ('Co', 'Nd', 'O'),
    ('Co', 'O', 'Pr'),
    ('Co', 'O', 'Ru'),
    ('Co', 'O', 'Si'),
    ('Co', 'O', 'Sr'),
    ('Co', 'O', 'U'),
    ('Co', 'O', 'V'),
    ('Co', 'O', 'Zn'),
    ('Cr', 'Dy', 'O'),
    ('Cr', 'Fe', 'O'),
    ('Cr', 'La', 'O'),
    ('Cr', 'Li', 'O'),
    ('Cr', 'Mn', 'O'),
    ('Cr', 'Ni', 'O'),
    ('Cr', 'O', 'Pb'),
    ('Cs', 'H', 'O', 'P'),
    ('Cs', 'In', 'O', 'Te'),
    ('Cs', 'Mo', 'O'),
    ('Cs', 'O', 'V'),
    ('Cu', 'Eu', 'O'),
    ('Cu', 'La', 'O'),
    ('Cu', 'Li', 'O'),
    ('Cu', 'Na', 'O', 'P'),
    ('Cu', 'Nd', 'O'),
    ('Cu', 'O', 'Pr'),
    ('Cu', 'O', 'Sb'),
    ('Cu', 'O', 'W'),
    ('Cu', 'O', 'Y'),
    ('Dy', 'Mo', 'O'),
    ('Dy', 'O', 'Ti'),
    ('Er', 'La', 'O'),
    ('Er', 'Mo', 'O'),
    ('Er', 'O', 'Si'),
    ('Er', 'O', 'V'),
    ('Eu', 'Ir', 'O'),
    ('Eu', 'O', 'Ti'),
    ('Eu', 'O', 'V'),
    ('F', 'Na', 'O', 'W'),
    ('Fe', 'In', 'O'),
    ('Fe', 'La', 'O'),
    ('Fe', 'Li', 'O', 'P'),
    ('Fe', 'Li', 'O', 'Si'),
    ('Fe', 'Mg', 'O'),
    ('Fe', 'Mo', 'O'),
    ('Fe', 'Na', 'O'),
    ('Fe', 'Na', 'O', 'P'),
    ('Fe', 'Nd', 'O'),
    ('Fe', 'O', 'Sm'),
    ('Fe', 'O', 'Ta'),
    ('Fe', 'O', 'Tm'),
    ('Fe', 'O', 'V', 'Zn'),
    ('Fe', 'O', 'Y'),
    ('Fe', 'O', 'Zn'),
    ('Ga', 'Ho', 'O'),
    ('Ga', 'La', 'O'),
    ('Ga', 'La', 'O', 'S'),
    ('Ga', 'Li', 'O'),
    ('Ga', 'Na', 'O'),
    ('Ga', 'Ni', 'O'),
    ('Ga', 'O', 'Sm'),
    ('Ga', 'O', 'Ti'),
    ('Gd', 'Ge', 'O'),
    ('Gd', 'In', 'O'),
    ('Gd', 'Mo', 'O'),
    ('Gd', 'O', 'Ru'),
    ('Gd', 'O', 'S'),
    ('Gd', 'O', 'Si'),
    ('Gd', 'O', 'Zr'),
    ('Ge', 'Ho', 'O'),
    ('Ge', 'K', 'O'),
    ('Ge', 'La', 'O'),
    ('Ge', 'Mn', 'O'),
    ('Ge', 'O', 'Te'),
    ('H', 'O', 'P', 'Rb'),
    ('H', 'O', 'Rb', 'S'),
    ('Hf', 'Lu', 'O'),
    ('Hf', 'O', 'Si'),
    ('Hf', 'O', 'Sr'),
    ('Hf', 'O', 'Ti'),
    ('Hf', 'O', 'Zr'),
    ('Ho', 'O', 'Ti'),
    ('Ho', 'O', 'W'),
    ('In', 'La', 'O'),
    ('In', 'Mo', 'O'),
    ('In', 'O', 'P'),
    ('In', 'O', 'Sn'),
    ('Ir', 'Na', 'O'),
    ('Ir', 'O', 'Pr'),
    ('Ir', 'O', 'Sr'),
    ('Ir', 'O', 'Y'),
    ('K', 'Li', 'O', 'S'),
    ('K', 'Mn', 'O'),
    ('K', 'Mo', 'O'),
    ('K', 'Na', 'Nb', 'O'),
    ('K', 'Na', 'O', 'Ru'),
    ('K', 'Na', 'O', 'S'),
    ('K', 'Nb', 'O'),
    ('K', 'O', 'Sb'),
    ('K', 'O', 'Si'),
    ('K', 'O', 'Ta'),
    ('K', 'O', 'Ti'),
    ('K', 'O', 'U'),
    ('K', 'O', 'V'),
    ('K', 'O', 'W'),
    ('La', 'Li', 'O'),
    ('La', 'Ni', 'O'),
    ('La', 'O', 'S'),
    ('La', 'O', 'Sb'),
    ('La', 'O', 'Si'),
    ('La', 'O', 'Zr'),
    ('Li', 'Mn', 'O', 'Ti'),
    ('Li', 'Mo', 'O'),
    ('Li', 'Nb', 'O'),
    ('Li', 'O', 'Ru'),
    ('Li', 'O', 'Sc'),
    ('Li', 'O', 'Sn'),
    ('Li', 'O', 'V'),
    ('Li', 'O', 'W'),
    ('Lu', 'O', 'Sr'),
    ('Lu', 'O', 'Ti'),
    ('Lu', 'O', 'V'),
    ('Mg', 'O', 'P'),
    ('Mg', 'O', 'Pu'),
    ('Mg', 'O', 'Sn'),
    ('Mn', 'Na', 'O'),
    ('Mn', 'Nd', 'O'),
    ('Mn', 'Ni', 'O'),
    ('Mn', 'O', 'Si'),
    ('Mn', 'O', 'Sm'),
    ('Mn', 'O', 'Sn'),
    ('Mn', 'O', 'Te'),
    ('Mn', 'O', 'W'),
    ('Mn', 'O', 'Y'),
    ('Mo', 'Na', 'O'),
    ('Mo', 'Nd', 'O', 'Tl'),
    ('Mo', 'O', 'Rb'),
    ('Mo', 'O', 'Sr'),
    ('Mo', 'O', 'Th'),
    ('Mo', 'O', 'Tl'),
    ('Mo', 'O', 'Zr'),
    ('Na', 'Nb', 'O'),
    ('Na', 'Ni', 'O'),
    ('Na', 'Np', 'O'),
    ('Na', 'O', 'Os'),
    ('Na', 'O', 'Pd'),
    ('Na', 'O', 'Rb', 'Ru'),
    ('Na', 'O', 'Rh'),
    ('Na', 'O', 'Ru'),
    ('Na', 'O', 'Sb'),
    ('Na', 'O', 'Te'),
    ('Na', 'O', 'Ti'),
    ('Na', 'O', 'V'),
    ('Nb', 'O', 'Sm'),
    ('Nb', 'O', 'Sn'),
    ('Nb', 'O', 'Ti'),
    ('Nb', 'O', 'Y'),
    ('Nb', 'O', 'Zn'),
    ('Nd', 'Ni', 'O'),
    ('Nd', 'O', 'Ru'),
    ('Nd', 'O', 'Sn'),
    ('Nd', 'O', 'W'),
    ('Ni', 'O', 'Ti'),
    ('Ni', 'O', 'Zn'),
    ('O', 'Os', 'Sm'),
    ('O', 'Os', 'Sr'),
    ('O', 'P', 'Sn'),
    ('O', 'P', 'Zn'),
    ('O', 'P', 'Zr'),
    ('O', 'Pb', 'Pd'),
    ('O', 'Pd', 'Sm'),
    ('O', 'Pd', 'Sr'),
    ('O', 'Pr', 'Sr'),
    ('O', 'Pu', 'Sr'),
    ('O', 'Pu', 'Te'),
    ('O', 'Rb', 'Ta'),
    ('O', 'Rh', 'Sm'),
    ('O', 'Rh', 'Y'),
    ('O', 'Rh', 'Zn'),
    ('O', 'Ru', 'Sr'),
    ('O', 'Ru', 'Y'),
    ('O', 'S', 'Sm'),
    ('O', 'Sb', 'Zn'),
    ('O', 'Sc', 'Si'),
    ('O', 'Sc', 'W'),
    ('O', 'Si', 'Sr'),
    ('O', 'Si', 'Zr'),
    ('O', 'Sm', 'Sn'),
    ('O', 'Sn', 'Te'),
    ('O', 'Sn', 'Ti'),
    ('O', 'Sn', 'Zn'),
    ('O', 'Sr', 'Ti'),
    ('O', 'Sr', 'V'),
    ('O', 'Sr', 'W'),
    ('O', 'Sr', 'Zr'),
    ('O', 'Ta', 'Zn'),
    ('O', 'Te', 'Ti'),
    ('O', 'Te', 'Zn'),
    ('O', 'Te', 'Zr'),
    ('O', 'Th', 'Ti'),
    ('O', 'Ti', 'Y'),
    ('O', 'V', 'Zr'),
    ('O', 'W', 'Y'),
    ('O', 'W', 'Zn'),
    ('O', 'Y', 'Zr')]

def get_batch(systems):
    name = "_".join(["-".join(system) for system in systems])
    batch = f"#!/bin/bash -l\n#SBATCH --account=cbartel\n#SBATCH --error=log_{name}.e\n#SBATCH --mem-per-cpu=1900M\n#SBATCH --nodes=1\n#SBATCH --ntasks=16\n#SBATCH --output=log_{name}.o\n#SBATCH --partition=msismall\n#SBATCH --time=2880\n#SBATCH --job-name=chemeleon_generation_{name}\nsource activate chemeleon\ncd ..\ncd gen_scripts_2\npython chemeleon_generation_{name}.py"
    return batch

def write_batch(batch, filename):
    with open(filename, 'w') as f:
        f.write(batch)
    print(f"Batch script written to {filename}")

def get_script(systems, save_dir, results_file):
    script = f"from pydmclab.utils.handy import read_json, write_json\nimport sys, os\ncurrent_dir = os.path.dirname(os.path.abspath(__file__))\nparent_dir = os.path.dirname(current_dir)\nsys.path.append(parent_dir)\nfrom generative_analysis import GenerateMaterials\n\nif __name__ == \"__main__\":\n    gm = GenerateMaterials(systems={str(systems)}, n_samples=5, max_stoich=8, max_natoms=25, max_factor=8, max_comps=50, save_dir=\"{save_dir}\")\n    results = gm.get_struct_stabilities(verbose=True, save_relaxed_cifs=True)\n    write_json(results, \"{results_file}\")"
    return script

def write_script(script, filename):
    with open(filename, 'w') as f:
        f.write(script)
    print(f"Script written to {filename}")

def group_list(lst, group_size):
    return [lst[i:i + group_size] for i in range(0, len(lst), group_size)]

if __name__ == "__main__":
    system_groups = group_list(SYSTEMS, 3)
    for systems in system_groups:
        name = "_".join(["-".join(system) for system in systems])
        script_name = f"chemeleon_generation_{name}.py"
        batch_name = f"batch_{name}.sh"

        script = get_script(systems, "./../run_results", f"./../run_results/{name}_results.json")
        write_script(script, os.path.join("gen_scripts_2", script_name))

        batch = get_batch(systems)
        write_batch(batch, os.path.join("gen_jobs_2", batch_name))


